apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-quote
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: quote.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dotnet-quote
                port:
                  number: 80
